name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Provider (Theme)
  path_provider: ^2.1.3
  provider: ^6.1.2

  #Slider
  flutter_slidable: ^3.1.1

  #State Management
  flutter_bloc: ^8.0.8

  #Chopper API
  chopper: ^8.0.1+1

  #Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  #Generate
  build_runner:

  #Chopper API
  chopper_generator: ^8.0.1

  #Local Storage
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
